FROM chip-config.img

MAINTAINER rhodey@anhonestefort.org

ARG CC_TOOL=/usr/bin/arm-linux-gnueabihf-

ARG BASE_DIR
ARG MAKE_J

ARG KERNEL_DIR=${BASE_DIR}/kernel
ARG MOD_DIR=${BASE_DIR}/module
ARG RTL_DIR=${BASE_DIR}/RTL8723BS

WORKDIR ${KERNEL_DIR}

RUN make ARCH=arm CROSS_COMPILE=${CC_TOOL} -j ${MAKE_J}
RUN make ARCH=arm CROSS_COMPILE=${CC_TOOL} INSTALL_MOD_PATH=${MOD_DIR} modules_install

WORKDIR ${RTL_DIR}

RUN make CONFIG_PLATFORM_ARM_SUNxI=y ARCH=arm CROSS_COMPILE=${CC_TOOL} \
  -C ${KERNEL_DIR}/ M=$PWD CONFIG_RTL8723BS=m INSTALL_MOD_PATH=${MOD_DIR} -j ${MAKE_J}

RUN make CONFIG_PLATFORM_ARM_SUNxI=y ARCH=arm CROSS_COMPILE=${CC_TOOL} \
  -C ${KERNEL_DIR}/ M=$PWD CONFIG_RTL8723BS=m  INSTALL_MOD_PATH=${MOD_DIR} modules_install -j ${MAKE_J}
