FROM chip-config.img

MAINTAINER rhodey@anhonestefort.org

ARG CC_TOOL=/usr/bin/arm-linux-gnueabihf-

ARG BASE_DIR
ARG MAKE_J

ARG KERNEL_DIR=${BASE_DIR}/kernel
ARG MOD_DIR=${BASE_DIR}/module
ARG RTL_DIR=${BASE_DIR}/RTL8723BS

WORKDIR ${KERNEL_DIR}

ARG KBUILD_DEBARCH=armhf
ARG KDEB_CHANGELOG_DIST=jessie
ARG LOCALVERSION=-version
RUN make ARCH=arm CROSS_COMPILE=${CC_TOOL} -j ${MAKE_J} deb-pkg
